### ISSUE TITLE
Is this going to be an official project?

### ISSUE THREAD

**Issue by making** [dsyer/spring-security-rsa#3]
Hi
Do you have a plan to promote `spring-security-rsa` to spring-security's project?
This project is used by [spring-cloud-common](https://github.com/spring-cloud/spring-cloud-commons/blob/1.0.2.RELEASE/spring-cloud-context/pom.xml#L41-L45).
I wonder why this is not under the [spring-security](https://github.com/spring-projects/spring-security).

I would like to use official `RsaSecretEncryptor`.
I hope this project to be managed by Spring IO Platform.

**Comment by btshimizukza** [comment]
:+1:

**Comment by ikeyat** [comment]
:+1:

**Comment by dsyer** [comment]
It's probably going to be in Spring Security sometime soonish, so just use it from here until such time as we merge it.
