### ISSUE TITLE
Update bouncycastle version to 1.59

### ISSUE THREAD

**Issue by gerardszczepanski** [dsyer/spring-security-rsa#9]
Please update bouncycastle version to 1.59

**Comment by larrywest** [comment]
FYI, this would appear to have been done &mdash; updated to 1.60 &mdash; in [commit #0f106d6](https://github.com/dsyer/spring-security-rsa/commit/0f106d6ccc30d56a4ae762d0193b90ff77e53c85) on August 1st, and incorporated in `1.0.6.RELEASE` (but `1.0.8.RELEASE` has an important fix).
